// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/protobuf/spec.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadConfigRequest) Reset() {
	*x = ReadConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfigRequest) ProtoMessage() {}

func (x *ReadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReadConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{0}
}

type ReadConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadConfigResponse) Reset() {
	*x = ReadConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfigResponse) ProtoMessage() {}

func (x *ReadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReadConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{1}
}

type ReadTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadTimeRequest) Reset() {
	*x = ReadTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTimeRequest) ProtoMessage() {}

func (x *ReadTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTimeRequest.ProtoReflect.Descriptor instead.
func (*ReadTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{2}
}

type ReadTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadTimeResponse) Reset() {
	*x = ReadTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTimeResponse) ProtoMessage() {}

func (x *ReadTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTimeResponse.ProtoReflect.Descriptor instead.
func (*ReadTimeResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{3}
}

type SetTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year   uint32 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month  uint32 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day    uint32 `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Hour   uint32 `protobuf:"varint,4,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute uint32 `protobuf:"varint,5,opt,name=minute,proto3" json:"minute,omitempty"`
	Second uint32 `protobuf:"varint,6,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *SetTimeRequest) Reset() {
	*x = SetTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimeRequest) ProtoMessage() {}

func (x *SetTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimeRequest.ProtoReflect.Descriptor instead.
func (*SetTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{4}
}

func (x *SetTimeRequest) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *SetTimeRequest) GetMonth() uint32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *SetTimeRequest) GetDay() uint32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *SetTimeRequest) GetHour() uint32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *SetTimeRequest) GetMinute() uint32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

func (x *SetTimeRequest) GetSecond() uint32 {
	if x != nil {
		return x.Second
	}
	return 0
}

type SetTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetTimeResponse) Reset() {
	*x = SetTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimeResponse) ProtoMessage() {}

func (x *SetTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimeResponse.ProtoReflect.Descriptor instead.
func (*SetTimeResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{5}
}

type SetCoefficients1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *SetCoefficients1Request) Reset() {
	*x = SetCoefficients1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCoefficients1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCoefficients1Request) ProtoMessage() {}

func (x *SetCoefficients1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCoefficients1Request.ProtoReflect.Descriptor instead.
func (*SetCoefficients1Request) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{6}
}

func (x *SetCoefficients1Request) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type SetCoefficients1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetCoefficients1Response) Reset() {
	*x = SetCoefficients1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCoefficients1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCoefficients1Response) ProtoMessage() {}

func (x *SetCoefficients1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCoefficients1Response.ProtoReflect.Descriptor instead.
func (*SetCoefficients1Response) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{7}
}

type ReadCoefficients1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadCoefficients1Request) Reset() {
	*x = ReadCoefficients1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCoefficients1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCoefficients1Request) ProtoMessage() {}

func (x *ReadCoefficients1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCoefficients1Request.ProtoReflect.Descriptor instead.
func (*ReadCoefficients1Request) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{8}
}

type ReadCoefficients1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadCoefficients1Response) Reset() {
	*x = ReadCoefficients1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCoefficients1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCoefficients1Response) ProtoMessage() {}

func (x *ReadCoefficients1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCoefficients1Response.ProtoReflect.Descriptor instead.
func (*ReadCoefficients1Response) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{9}
}

type SetCoefficients2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ax1   float32 `protobuf:"fixed32,1,opt,name=ax1,proto3" json:"ax1,omitempty"`
	Ay1   float32 `protobuf:"fixed32,2,opt,name=ay1,proto3" json:"ay1,omitempty"`
	Az1   float32 `protobuf:"fixed32,3,opt,name=az1,proto3" json:"az1,omitempty"`
	Beta  float32 `protobuf:"fixed32,4,opt,name=beta,proto3" json:"beta,omitempty"`
	Gamma float32 `protobuf:"fixed32,5,opt,name=gamma,proto3" json:"gamma,omitempty"`
	Xi    float32 `protobuf:"fixed32,6,opt,name=xi,proto3" json:"xi,omitempty"`
	Exy   float32 `protobuf:"fixed32,7,opt,name=exy,proto3" json:"exy,omitempty"`
	Eyz   float32 `protobuf:"fixed32,8,opt,name=eyz,proto3" json:"eyz,omitempty"`
	Exz   float32 `protobuf:"fixed32,9,opt,name=exz,proto3" json:"exz,omitempty"`
	K1X   float32 `protobuf:"fixed32,10,opt,name=k1x,proto3" json:"k1x,omitempty"`
	K1Y   float32 `protobuf:"fixed32,11,opt,name=k1y,proto3" json:"k1y,omitempty"`
	K1Z   float32 `protobuf:"fixed32,12,opt,name=k1z,proto3" json:"k1z,omitempty"`
	K2X   float32 `protobuf:"fixed32,13,opt,name=k2x,proto3" json:"k2x,omitempty"`
	K2Y   float32 `protobuf:"fixed32,14,opt,name=k2y,proto3" json:"k2y,omitempty"`
	K2Z   float32 `protobuf:"fixed32,15,opt,name=k2z,proto3" json:"k2z,omitempty"`
	Ktf   float32 `protobuf:"fixed32,16,opt,name=ktf,proto3" json:"ktf,omitempty"`
	Kte   float32 `protobuf:"fixed32,17,opt,name=kte,proto3" json:"kte,omitempty"`
	Ktf0  float32 `protobuf:"fixed32,18,opt,name=ktf0,proto3" json:"ktf0,omitempty"`
	Kte0  float32 `protobuf:"fixed32,19,opt,name=kte0,proto3" json:"kte0,omitempty"`
	Kvbat float32 `protobuf:"fixed32,20,opt,name=kvbat,proto3" json:"kvbat,omitempty"`
}

func (x *SetCoefficients2Request) Reset() {
	*x = SetCoefficients2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCoefficients2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCoefficients2Request) ProtoMessage() {}

func (x *SetCoefficients2Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCoefficients2Request.ProtoReflect.Descriptor instead.
func (*SetCoefficients2Request) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{10}
}

func (x *SetCoefficients2Request) GetAx1() float32 {
	if x != nil {
		return x.Ax1
	}
	return 0
}

func (x *SetCoefficients2Request) GetAy1() float32 {
	if x != nil {
		return x.Ay1
	}
	return 0
}

func (x *SetCoefficients2Request) GetAz1() float32 {
	if x != nil {
		return x.Az1
	}
	return 0
}

func (x *SetCoefficients2Request) GetBeta() float32 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *SetCoefficients2Request) GetGamma() float32 {
	if x != nil {
		return x.Gamma
	}
	return 0
}

func (x *SetCoefficients2Request) GetXi() float32 {
	if x != nil {
		return x.Xi
	}
	return 0
}

func (x *SetCoefficients2Request) GetExy() float32 {
	if x != nil {
		return x.Exy
	}
	return 0
}

func (x *SetCoefficients2Request) GetEyz() float32 {
	if x != nil {
		return x.Eyz
	}
	return 0
}

func (x *SetCoefficients2Request) GetExz() float32 {
	if x != nil {
		return x.Exz
	}
	return 0
}

func (x *SetCoefficients2Request) GetK1X() float32 {
	if x != nil {
		return x.K1X
	}
	return 0
}

func (x *SetCoefficients2Request) GetK1Y() float32 {
	if x != nil {
		return x.K1Y
	}
	return 0
}

func (x *SetCoefficients2Request) GetK1Z() float32 {
	if x != nil {
		return x.K1Z
	}
	return 0
}

func (x *SetCoefficients2Request) GetK2X() float32 {
	if x != nil {
		return x.K2X
	}
	return 0
}

func (x *SetCoefficients2Request) GetK2Y() float32 {
	if x != nil {
		return x.K2Y
	}
	return 0
}

func (x *SetCoefficients2Request) GetK2Z() float32 {
	if x != nil {
		return x.K2Z
	}
	return 0
}

func (x *SetCoefficients2Request) GetKtf() float32 {
	if x != nil {
		return x.Ktf
	}
	return 0
}

func (x *SetCoefficients2Request) GetKte() float32 {
	if x != nil {
		return x.Kte
	}
	return 0
}

func (x *SetCoefficients2Request) GetKtf0() float32 {
	if x != nil {
		return x.Ktf0
	}
	return 0
}

func (x *SetCoefficients2Request) GetKte0() float32 {
	if x != nil {
		return x.Kte0
	}
	return 0
}

func (x *SetCoefficients2Request) GetKvbat() float32 {
	if x != nil {
		return x.Kvbat
	}
	return 0
}

type SetCoefficients2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetCoefficients2Response) Reset() {
	*x = SetCoefficients2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCoefficients2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCoefficients2Response) ProtoMessage() {}

func (x *SetCoefficients2Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCoefficients2Response.ProtoReflect.Descriptor instead.
func (*SetCoefficients2Response) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{11}
}

type ReadCoefficients2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadCoefficients2Request) Reset() {
	*x = ReadCoefficients2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCoefficients2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCoefficients2Request) ProtoMessage() {}

func (x *ReadCoefficients2Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCoefficients2Request.ProtoReflect.Descriptor instead.
func (*ReadCoefficients2Request) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{12}
}

type ReadCoefficients2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadCoefficients2Response) Reset() {
	*x = ReadCoefficients2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCoefficients2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCoefficients2Response) ProtoMessage() {}

func (x *ReadCoefficients2Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCoefficients2Response.ProtoReflect.Descriptor instead.
func (*ReadCoefficients2Response) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{13}
}

type ReadGPSDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadGPSDataRequest) Reset() {
	*x = ReadGPSDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadGPSDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGPSDataRequest) ProtoMessage() {}

func (x *ReadGPSDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGPSDataRequest.ProtoReflect.Descriptor instead.
func (*ReadGPSDataRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{14}
}

type ReadGPSDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadGPSDataResponse) Reset() {
	*x = ReadGPSDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadGPSDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGPSDataResponse) ProtoMessage() {}

func (x *ReadGPSDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGPSDataResponse.ProtoReflect.Descriptor instead.
func (*ReadGPSDataResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{15}
}

type StopSystemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopSystemRequest) Reset() {
	*x = StopSystemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSystemRequest) ProtoMessage() {}

func (x *StopSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSystemRequest.ProtoReflect.Descriptor instead.
func (*StopSystemRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{16}
}

type StopSystemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopSystemResponse) Reset() {
	*x = StopSystemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSystemResponse) ProtoMessage() {}

func (x *StopSystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSystemResponse.ProtoReflect.Descriptor instead.
func (*StopSystemResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{17}
}

type StartSystemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartSystemRequest) Reset() {
	*x = StartSystemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSystemRequest) ProtoMessage() {}

func (x *StartSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSystemRequest.ProtoReflect.Descriptor instead.
func (*StartSystemRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{18}
}

type StartSystemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartSystemResponse) Reset() {
	*x = StartSystemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSystemResponse) ProtoMessage() {}

func (x *StartSystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSystemResponse.ProtoReflect.Descriptor instead.
func (*StartSystemResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{19}
}

type CheckFLASHRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckFLASHRequest) Reset() {
	*x = CheckFLASHRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFLASHRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFLASHRequest) ProtoMessage() {}

func (x *CheckFLASHRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFLASHRequest.ProtoReflect.Descriptor instead.
func (*CheckFLASHRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{20}
}

type CheckFLASHResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckFLASHResponse) Reset() {
	*x = CheckFLASHResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFLASHResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFLASHResponse) ProtoMessage() {}

func (x *CheckFLASHResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFLASHResponse.ProtoReflect.Descriptor instead.
func (*CheckFLASHResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{21}
}

type SetDACxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"zigzag32,1,opt,name=x,proto3" json:"x,omitempty"`
}

func (x *SetDACxRequest) Reset() {
	*x = SetDACxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDACxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDACxRequest) ProtoMessage() {}

func (x *SetDACxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDACxRequest.ProtoReflect.Descriptor instead.
func (*SetDACxRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{22}
}

func (x *SetDACxRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

type SetDACxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetDACxResponse) Reset() {
	*x = SetDACxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDACxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDACxResponse) ProtoMessage() {}

func (x *SetDACxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDACxResponse.ProtoReflect.Descriptor instead.
func (*SetDACxResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{23}
}

type SetDACyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Y int32 `protobuf:"zigzag32,1,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *SetDACyRequest) Reset() {
	*x = SetDACyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDACyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDACyRequest) ProtoMessage() {}

func (x *SetDACyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDACyRequest.ProtoReflect.Descriptor instead.
func (*SetDACyRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{24}
}

func (x *SetDACyRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SetDACyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetDACyResponse) Reset() {
	*x = SetDACyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDACyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDACyResponse) ProtoMessage() {}

func (x *SetDACyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDACyResponse.ProtoReflect.Descriptor instead.
func (*SetDACyResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{25}
}

type SetDACzRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Z int32 `protobuf:"zigzag32,1,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *SetDACzRequest) Reset() {
	*x = SetDACzRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDACzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDACzRequest) ProtoMessage() {}

func (x *SetDACzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDACzRequest.ProtoReflect.Descriptor instead.
func (*SetDACzRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{26}
}

func (x *SetDACzRequest) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type SetDACzResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetDACzResponse) Reset() {
	*x = SetDACzResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDACzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDACzResponse) ProtoMessage() {}

func (x *SetDACzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDACzResponse.ProtoReflect.Descriptor instead.
func (*SetDACzResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_proto_rawDescGZIP(), []int{27}
}

var File_api_protobuf_spec_proto protoreflect.FileDescriptor

var file_api_protobuf_spec_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11,
	0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x6f, 0x6e,
	0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x64, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x68, 0x6f, 0x75, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x75,
	0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x17, 0x53,
	0x65, 0x74, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x65,
	0x74, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x31, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f,
	0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69,
	0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x8d, 0x03, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65,
	0x6e, 0x74, 0x73, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x78, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x61, 0x78, 0x31, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x79, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x61, 0x79, 0x31, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x7a, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x61, 0x7a,
	0x31, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x62, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x61, 0x6d, 0x6d, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x6d, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x78,
	0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x78, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x78, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x65, 0x78, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x79, 0x7a, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x65, 0x79, 0x7a, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x78, 0x7a, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x65, 0x78,
	0x7a, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x31, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03,
	0x6b, 0x31, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x31, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x6b, 0x31, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x31, 0x7a, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x6b, 0x31, 0x7a, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x32, 0x78, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6b, 0x32, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x32, 0x79,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6b, 0x32, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x32, 0x7a, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6b, 0x32, 0x7a, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x74, 0x66, 0x18, 0x10, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6b, 0x74, 0x66, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x74, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6b, 0x74,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x74, 0x66, 0x30, 0x18, 0x12, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x6b, 0x74, 0x66, 0x30, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x74, 0x65, 0x30, 0x18, 0x13, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x6b, 0x74, 0x65, 0x30, 0x12, 0x14, 0x0a, 0x05, 0x6b, 0x76, 0x62,
	0x61, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x6b, 0x76, 0x62, 0x61, 0x74, 0x22,
	0x1a, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x52,
	0x65, 0x61, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x32,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x61, 0x64, 0x43,
	0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x32, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x47, 0x50, 0x53, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65,
	0x61, 0x64, 0x47, 0x50, 0x53, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x46, 0x4c, 0x41, 0x53, 0x48, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14,
	0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x4c, 0x41, 0x53, 0x48, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x44, 0x41, 0x43, 0x78, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x11, 0x52, 0x01, 0x78, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x44, 0x41, 0x43, 0x78, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x44, 0x41,
	0x43, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x11, 0x52, 0x01, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x44, 0x41,
	0x43, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x0e, 0x53, 0x65,
	0x74, 0x44, 0x41, 0x43, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01,
	0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x01, 0x7a, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65,
	0x74, 0x44, 0x41, 0x43, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd4, 0x08,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x49, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x08, 0x52,
	0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5b, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x31, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74,
	0x73, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5e, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65,
	0x6e, 0x74, 0x73, 0x31, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5b, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x32, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x65, 0x74, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x32, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74,
	0x73, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x11,
	0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x32, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x32, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74,
	0x73, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b,
	0x52, 0x65, 0x61, 0x64, 0x47, 0x50, 0x53, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x47, 0x50, 0x53, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x47, 0x50, 0x53, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a, 0x53, 0x74,
	0x6f, 0x70, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x4c, 0x41, 0x53,
	0x48, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x46, 0x4c, 0x41, 0x53, 0x48, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46,
	0x4c, 0x41, 0x53, 0x48, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40,
	0x0a, 0x07, 0x53, 0x65, 0x74, 0x44, 0x41, 0x43, 0x78, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x41, 0x43, 0x78, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x65, 0x74, 0x44, 0x41, 0x43, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x44, 0x41, 0x43, 0x79, 0x12, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x41, 0x43, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x65, 0x74, 0x44, 0x41, 0x43, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x40, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x44, 0x41, 0x43, 0x7a, 0x12, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x41, 0x43, 0x7a,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x41, 0x43, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x73, 0x73, 0x2d, 0x65, 0x64, 0x61, 0x2f, 0x6c, 0x65, 0x6d, 0x69, 0x30,
	0x32, 0x35, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protobuf_spec_proto_rawDescOnce sync.Once
	file_api_protobuf_spec_proto_rawDescData = file_api_protobuf_spec_proto_rawDesc
)

func file_api_protobuf_spec_proto_rawDescGZIP() []byte {
	file_api_protobuf_spec_proto_rawDescOnce.Do(func() {
		file_api_protobuf_spec_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protobuf_spec_proto_rawDescData)
	})
	return file_api_protobuf_spec_proto_rawDescData
}

var file_api_protobuf_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_protobuf_spec_proto_goTypes = []interface{}{
	(*ReadConfigRequest)(nil),         // 0: protobuf.ReadConfigRequest
	(*ReadConfigResponse)(nil),        // 1: protobuf.ReadConfigResponse
	(*ReadTimeRequest)(nil),           // 2: protobuf.ReadTimeRequest
	(*ReadTimeResponse)(nil),          // 3: protobuf.ReadTimeResponse
	(*SetTimeRequest)(nil),            // 4: protobuf.SetTimeRequest
	(*SetTimeResponse)(nil),           // 5: protobuf.SetTimeResponse
	(*SetCoefficients1Request)(nil),   // 6: protobuf.SetCoefficients1Request
	(*SetCoefficients1Response)(nil),  // 7: protobuf.SetCoefficients1Response
	(*ReadCoefficients1Request)(nil),  // 8: protobuf.ReadCoefficients1Request
	(*ReadCoefficients1Response)(nil), // 9: protobuf.ReadCoefficients1Response
	(*SetCoefficients2Request)(nil),   // 10: protobuf.SetCoefficients2Request
	(*SetCoefficients2Response)(nil),  // 11: protobuf.SetCoefficients2Response
	(*ReadCoefficients2Request)(nil),  // 12: protobuf.ReadCoefficients2Request
	(*ReadCoefficients2Response)(nil), // 13: protobuf.ReadCoefficients2Response
	(*ReadGPSDataRequest)(nil),        // 14: protobuf.ReadGPSDataRequest
	(*ReadGPSDataResponse)(nil),       // 15: protobuf.ReadGPSDataResponse
	(*StopSystemRequest)(nil),         // 16: protobuf.StopSystemRequest
	(*StopSystemResponse)(nil),        // 17: protobuf.StopSystemResponse
	(*StartSystemRequest)(nil),        // 18: protobuf.StartSystemRequest
	(*StartSystemResponse)(nil),       // 19: protobuf.StartSystemResponse
	(*CheckFLASHRequest)(nil),         // 20: protobuf.CheckFLASHRequest
	(*CheckFLASHResponse)(nil),        // 21: protobuf.CheckFLASHResponse
	(*SetDACxRequest)(nil),            // 22: protobuf.SetDACxRequest
	(*SetDACxResponse)(nil),           // 23: protobuf.SetDACxResponse
	(*SetDACyRequest)(nil),            // 24: protobuf.SetDACyRequest
	(*SetDACyResponse)(nil),           // 25: protobuf.SetDACyResponse
	(*SetDACzRequest)(nil),            // 26: protobuf.SetDACzRequest
	(*SetDACzResponse)(nil),           // 27: protobuf.SetDACzResponse
}
var file_api_protobuf_spec_proto_depIdxs = []int32{
	0,  // 0: protobuf.CommandService.ReadConfig:input_type -> protobuf.ReadConfigRequest
	2,  // 1: protobuf.CommandService.ReadTime:input_type -> protobuf.ReadTimeRequest
	4,  // 2: protobuf.CommandService.SetTime:input_type -> protobuf.SetTimeRequest
	6,  // 3: protobuf.CommandService.SetCoefficients1:input_type -> protobuf.SetCoefficients1Request
	8,  // 4: protobuf.CommandService.ReadCoefficients1:input_type -> protobuf.ReadCoefficients1Request
	10, // 5: protobuf.CommandService.SetCoefficients2:input_type -> protobuf.SetCoefficients2Request
	12, // 6: protobuf.CommandService.ReadCoefficients2:input_type -> protobuf.ReadCoefficients2Request
	14, // 7: protobuf.CommandService.ReadGPSData:input_type -> protobuf.ReadGPSDataRequest
	16, // 8: protobuf.CommandService.StopSystem:input_type -> protobuf.StopSystemRequest
	18, // 9: protobuf.CommandService.StartSystem:input_type -> protobuf.StartSystemRequest
	20, // 10: protobuf.CommandService.CheckFLASH:input_type -> protobuf.CheckFLASHRequest
	22, // 11: protobuf.CommandService.SetDACx:input_type -> protobuf.SetDACxRequest
	24, // 12: protobuf.CommandService.SetDACy:input_type -> protobuf.SetDACyRequest
	26, // 13: protobuf.CommandService.SetDACz:input_type -> protobuf.SetDACzRequest
	1,  // 14: protobuf.CommandService.ReadConfig:output_type -> protobuf.ReadConfigResponse
	3,  // 15: protobuf.CommandService.ReadTime:output_type -> protobuf.ReadTimeResponse
	5,  // 16: protobuf.CommandService.SetTime:output_type -> protobuf.SetTimeResponse
	7,  // 17: protobuf.CommandService.SetCoefficients1:output_type -> protobuf.SetCoefficients1Response
	9,  // 18: protobuf.CommandService.ReadCoefficients1:output_type -> protobuf.ReadCoefficients1Response
	11, // 19: protobuf.CommandService.SetCoefficients2:output_type -> protobuf.SetCoefficients2Response
	13, // 20: protobuf.CommandService.ReadCoefficients2:output_type -> protobuf.ReadCoefficients2Response
	15, // 21: protobuf.CommandService.ReadGPSData:output_type -> protobuf.ReadGPSDataResponse
	17, // 22: protobuf.CommandService.StopSystem:output_type -> protobuf.StopSystemResponse
	19, // 23: protobuf.CommandService.StartSystem:output_type -> protobuf.StartSystemResponse
	21, // 24: protobuf.CommandService.CheckFLASH:output_type -> protobuf.CheckFLASHResponse
	23, // 25: protobuf.CommandService.SetDACx:output_type -> protobuf.SetDACxResponse
	25, // 26: protobuf.CommandService.SetDACy:output_type -> protobuf.SetDACyResponse
	27, // 27: protobuf.CommandService.SetDACz:output_type -> protobuf.SetDACzResponse
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_protobuf_spec_proto_init() }
func file_api_protobuf_spec_proto_init() {
	if File_api_protobuf_spec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protobuf_spec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCoefficients1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCoefficients1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCoefficients1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCoefficients1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCoefficients2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCoefficients2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCoefficients2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCoefficients2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadGPSDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadGPSDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopSystemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopSystemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSystemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSystemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFLASHRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFLASHResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDACxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDACxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDACyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDACyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDACzRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDACzResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protobuf_spec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protobuf_spec_proto_goTypes,
		DependencyIndexes: file_api_protobuf_spec_proto_depIdxs,
		MessageInfos:      file_api_protobuf_spec_proto_msgTypes,
	}.Build()
	File_api_protobuf_spec_proto = out.File
	file_api_protobuf_spec_proto_rawDesc = nil
	file_api_protobuf_spec_proto_goTypes = nil
	file_api_protobuf_spec_proto_depIdxs = nil
}
